name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install schedule
        pip install pathlib
        pip install hashlib
        pip install logging
        pip install shutil
        pip install os
        pip install sys
        pip install time
    - name: Test with pytest
      run: |
        python -m pytest test_veem.py